# Generated by Django 5.2.8 on 2026-02-16 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_leavecategory_alter_user_managers_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='to_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='leavecategory',
            name='days_per_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
