# Generated by Django 5.2.8 on 2026-02-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_personaltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('LEAVE', 'Leave'), ('ATTENDANCE', 'Attendance'), ('EVENT', 'Event'), ('ANNOUNCEMENT', 'Announcement'), ('TIMELINE', 'Timeline'), ('SECURITY', 'Security')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
