# Generated by Django 5.2.8 on 2026-02-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_team'),
        ('hr', '0019_adminprofile'),
    ]

    operations = [
    ]
