# Generated by Django 5.2.8 on 2026-02-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_payroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='employee_id',
        ),
    ]
