# Generated by Django 5.2.8 on 2026-02-21 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_remove_payroll_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hr.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hr.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI'), ('CARD', 'Card')], max_length=10)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hr.invoice')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
