# Generated by Django 5.2.8 on 2026-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_options_payment_bank_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_ref',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
