# Generated by Django 5.2.8 on 2026-02-20 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_payment_bank_ref_alter_payment_card_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='client_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='member_since',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
