# Generated by Django 5.2.8 on 2026-02-20 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_clientprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='member_since',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
