# Generated by Django 5.2.8 on 2026-02-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_clientprofile_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('PROJECT', 'Project')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
    ]
