# Generated by Django 5.2.8 on 2026-02-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
