# Generated by Django 5.2.8 on 2026-02-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_invoice_client_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
