# Generated by Django 5.2.8 on 2026-03-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
