# Generated by Django 5.2.8 on 2026-02-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
