# Generated by Django 5.2.8 on 2026-02-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_attendance_options_alter_leaverequest_category_and_more'),
        ('hr', '0008_client'),
    ]

    operations = [
    ]
