# Generated by Django 5.2.11 on 2026-02-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
