# Generated by Django 5.2.11 on 2026-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_event_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
